"""Constants for the PlantRun integration."""

DOMAIN = "plantrun"
PLATFORMS = ["sensor"]

# Store constants
STORE_KEY = "plantrun_store"
STORE_VERSION = 2
STORE_SCHEMA_VERSION = 2

# Service attribute keys
ATTR_RUN_ID = "run_id"
ATTR_RUN_NAME = "run_name"
ATTR_USE_ACTIVE_RUN = "use_active_run"
ATTR_STRICT_ACTIVE_RESOLUTION = "strict_active_resolution"
ATTR_ACTIVE_RUN_STRATEGY = "active_run_strategy"

ACTIVE_RUN_STRATEGY_LEGACY = "legacy"
ACTIVE_RUN_STRATEGY_ACTIVE_RUN_ID = "active_run_id"
ACTIVE_RUN_STRATEGY_FIRST_ACTIVE = "first_active"
ACTIVE_RUN_STRATEGIES = [
    ACTIVE_RUN_STRATEGY_LEGACY,
    ACTIVE_RUN_STRATEGY_ACTIVE_RUN_ID,
    ACTIVE_RUN_STRATEGY_FIRST_ACTIVE,
]

# Metric binding constants
METRIC_TYPE_TEMPERATURE = "temperature"
METRIC_TYPE_HUMIDITY = "humidity"
METRIC_TYPE_SOIL_MOISTURE = "soil_moisture"
METRIC_TYPE_CONDUCTIVITY = "conductivity"
METRIC_TYPE_LIGHT = "light"
METRIC_TYPE_ENERGY = "energy"
METRIC_TYPE_WATER = "water"
METRIC_TYPE_CAMERA = "camera"

ALLOWED_METRIC_TYPES = [
    METRIC_TYPE_TEMPERATURE,
    METRIC_TYPE_HUMIDITY,
    METRIC_TYPE_SOIL_MOISTURE,
    METRIC_TYPE_CONDUCTIVITY,
    METRIC_TYPE_LIGHT,
    METRIC_TYPE_ENERGY,
    METRIC_TYPE_WATER,
    METRIC_TYPE_CAMERA,
]

UNSUPPORTED_BINDING_METRIC_TYPES = [
    METRIC_TYPE_CAMERA,
]

INITIAL_PHASE_NAME = "Seedling"
